"""File I/O operations for saving analysis results."""
import os
from datetime import datetime

def save_route_analysis(analysis, filename="flight_analysis.txt"):
    """
    Save flight route analysis to a text file.
    
    Args:
        analysis: FlightRoute or BatchAnalysis object
        filename: Output filename
    
    Returns:
        True if successful, False otherwise
    """
    try:
        # Create output directory if needed
        output_dir = os.path.dirname(filename)
        if output_dir and not os.path.exists(output_dir):
            os.makedirs(output_dir)
        
        with open(filename, 'w') as file:
            file.write("FLIGHT ROUTE ANALYSIS REPORT\n")
            file.write("="*60 + "\n")
            file.write(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
            file.write(f"Tool: Flight Path Distance Calculator\n")
            file.write("="*60 + "\n\n")
            
            # Handle single route
            if hasattr(analysis, 'origin') and hasattr(analysis, 'destination'):
                _write_single_route(file, analysis)
            
            # Handle batch analysis
            elif hasattr(analysis, 'routes'):
                _write_batch_analysis(file, analysis)
            
            file.write("\n" + "="*60)
            file.write("\nReport generated by Flight Path Distance Calculator")
        
        print(f"  Analysis saved to '{filename}'")
        return True
        
    except Exception as e:
        print(f"  Error saving analysis to '{filename}': {e}")
        return False


def _write_single_route(file, route):
    """Helper to write single route details to file."""
    file.write("SINGLE ROUTE ANALYSIS\n")
    file.write("-"*60 + "\n\n")
    
    file.write(f"Route: {route.origin.code} → {route.destination.code}\n")
    file.write(f"From: {route.origin.name} ({route.origin.city}, {route.origin.country})\n")
    file.write(f"To: {route.destination.name} ({route.destination.city}, {route.destination.country})\n")
    file.write(f"Coordinates: {route.origin.get_coordinates()} → {route.destination.get_coordinates()}\n\n")
    
    file.write("DISTANCE:\n")
    file.write(f"   Miles:          {route.distance_miles:,.2f}\n")
    file.write(f"   Kilometers:     {route.distance_km:,.2f}\n")
    file.write(f"   Nautical Miles: {route.distance_nautical_miles:,.2f}\n\n")
    
    file.write("NAVIGATION:\n")
    file.write(f"   Initial Bearing:    {route.bearing_degrees}°\n")
    file.write(f"   Compass Direction:  {route.compass_direction}\n\n")
    
    hours, minutes = route.get_duration_minutes()
    file.write("ESTIMATED FLIGHT TIME:\n")
    file.write(f"   Duration:     {hours}h {minutes}m\n")
    file.write(f"   Total Hours:  {route.estimated_flight_hours:.2f}\n")
    file.write(f"   (Based on 500 mph average speed)\n")


def _write_batch_analysis(file, analysis):
    """Helper to write batch analysis details to file."""
    file.write("BATCH ROUTE ANALYSIS\n")
    file.write("-"*60 + "\n\n")
    
    file.write("SUMMARY STATISTICS:\n")
    file.write(f"   Total Routes:        {analysis.get_total_routes()}\n")
    file.write(f"   Total Distance:      {analysis.total_distance_miles:,.2f} miles\n")
    file.write(f"   Average Distance:    {analysis.average_distance_miles:,.2f} miles\n")
    file.write(f"   Total Flight Time:   {analysis.total_flight_time_hours:.2f} hours\n")
    file.write(f"   Average Flight Time: {analysis.average_flight_time_hours:.2f} hours\n\n")
    
    if analysis.shortest_route:
        file.write("SHORTEST ROUTE:\n")
        file.write(f"   {analysis.shortest_route.origin.code} → {analysis.shortest_route.destination.code}\n")
        file.write(f"   Distance: {analysis.shortest_route.distance_miles:,.2f} miles\n")
        file.write(f"   Flight Time: {analysis.shortest_route.estimated_flight_hours:.2f} hours\n\n")
    
    if analysis.longest_route:
        file.write("LONGEST ROUTE:\n")
        file.write(f"   {analysis.longest_route.origin.code} → {analysis.longest_route.destination.code}\n")
        file.write(f"   Distance: {analysis.longest_route.distance_miles:,.2f} miles\n")
        file.write(f"   Flight Time: {analysis.longest_route.estimated_flight_hours:.2f} hours\n\n")
    
    file.write("ALL ROUTES:\n")
    file.write("-"*60 + "\n")
    for i, route in enumerate(analysis.routes, 1):
        file.write(f"\nRoute {i}: {route.origin.code} → {route.destination.code}\n")
        file.write(f"Distance: {route.distance_miles:,.2f} miles | "
                  f"Bearing: {route.bearing_degrees}° ({route.compass_direction}) | "
                  f"Time: {route.estimated_flight_hours:.2f}h")